### ISSUE TITLE
Error in Space/getTemplate ?

### ISSUE THREAD

**Issue by SBludau** [FZJ-INM1-BDA/siibra-matlab#10] opened 2022-03-03 15:39 UTC
Hi,
I just wanted to implement some small ideas with Matlab, and it occurred to me that I could test parts of them right away with siibra.

I tested some lines from the following example and got two different error messages.

```
% taken from 02_access_brain_reference_templates.mlx
siibra = Siibra();
human_atlas = siibra.Atlases.Atlas(1);
mni_asym = human_atlas.Spaces.Space(1);
mni_asym_template = mni_asym.getTemplate();
```

First time I tested the code:
```
Error using websave (line 104)
Unable to open output file: 'template_cache/MNI152 2009c nonl asym.nii' for writing. Common reasons
include that the file exists and does not have write permission or the folder does not have write
permissions.

Error in Space/getTemplate (line 29)
                websave(cached_path, obj.TemplateURL, options);
```

Second time I tested the code:
```
>> mni_asym_template = mni_asym.getTemplate();
Error using websave (line 98)
The connection to URL
'https://siibra-api-latest.apps-dev.hbp.eu/v1_0/atlases/juelich%2Fiav%2Fatlas%2Fv1.0.0%2F1/spaces/minds%2Fcore%2Freferencespace%2Fv1.0.0%2Fdafcffc5-4826-4bf1-8ff6-46b8a31ff8e2/templates'
timed out after 30.000 seconds. The reason is "Waiting for response header". Perhaps the server is
not responding or weboptions.Timeout needs to be set to a higher value.

Error in Space/getTemplate (line 29)
                websave(cached_path, obj.TemplateURL, options);_
```

Have I missed any settings? In the siibra/templates folder there is already the MNI152 template, can it be that the download collides with it?

best regards
Sebastian

**Comment by dickscheid** [comment] 2022-03-22 07:36
With the new update, your code becomes
``` python
mni152space = siibra.getSpace("MNI152 2009c nonl asym")
mni152tpl = mni152space.getTemplate()
```
But the error persists, it is due to the missing subfolder in the cache directory. This is thus directly related to #11

**Comment by dickscheid** [comment] 2022-03-22 07:39
Duplicate of #11

**Closed** 2022-04-04 09:41 UTC
Labels: bug, duplicate
